language: node_js
node_js: "8.9.4"
os:
- linux
- windows
dist: trusty
sudo: false

branches:
  only:
  - master
  
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

install:
- npm install
- npm update

script:
  - ng test --watch false -cc
  - npm run e2e
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master
