language: node_js
node_js: "8.9.4"

dist: trusty
sudo: false

branches:
  only:
  - master
  
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm
script: ./run_build.sh
install:
- npm install
- npm update

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master
